---
- name: 'extract zipped backend'
  become: yes
  copy:
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu/backend.tar.gz

- name: 'run node application'
  become: yes
  shell: |
    cd /home/ubuntu
    tar xzvf backend.tar.gz 
    npm i 
    npm run build
    pm2 stop default
    pm2 start npm -- start
